plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.13' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

allprojects {
    repositories {
        mavenCentral()
    }
}

tasks.register("collectJars", Copy) {
    group = "build"
    description = "Copy all JARs to dist/"

    into layout.buildDirectory.dir("dist")

    subprojects.each { subproject ->
        dependsOn subproject.tasks.matching { it.name == "build" }

        from (subproject.layout.buildDirectory.dir("libs")) {
            include("*${version}.jar")
            exclude("*-all.jar", "*-sources.jar", "*-javadoc.jar", "*common*")
        }
    }
}
