plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.31,8)'
    id 'com.gradleup.shadow' version '9.5.1'
    id 'idea'
    id 'com.diffplug.spotless' version '8.1.0'
}

spotless {
    setEnforceCheck(false)

    java {
        palantirJavaFormat()
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.client.mixins.json,${mod_id}.forge.mixins.json"
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    accessTransformers = files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('runs')
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            args "--mixin.config=authorisedkeysmc.mixins.json"
            args "--mixin.config=authorisedkeysmc.client.mixins.json"
            args "--mixin.config=authorisedkeysmc.forge.mixins.json"
        }

        register('client') {
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            systemProperty 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            systemProperty 'forge.logging.console.level', 'debug'
        }

        register('server') {
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            systemProperty 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            systemProperty 'forge.logging.console.level', 'debug'
            args '--nogui'
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url = 'https://maven.minecraftforge.net'
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")

    // Source: https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
    implementation "org.bouncycastle:bcprov-jdk18on:${bouncycastle_version}"
    shadow "org.bouncycastle:bcprov-jdk18on:${bouncycastle_version}"
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
