package ph.jldvmsrwll1a.authorisedkeysmc;

import java.io.*;
import java.nio.file.Files;
import java.util.Properties;

public final class ServerConfig {
    public boolean enforcing;
    public int loginTimeoutTicks;
    public boolean registrationRequired;
    public boolean allowRegistration;

    public void reset() {
        enforcing = true;
        loginTimeoutTicks = 1200;
        registrationRequired = false;
        allowRegistration = true;
    }

    public void read() {
        Properties props = new Properties();

        try (FileReader file = new FileReader(AuthorisedKeysModCore.FILE_PATHS.SERVER_CONFIG_PATH.toFile())) {
            props.load(file);
        } catch (FileNotFoundException e) {
            reset();

            return;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        String enforcingStr = props.getProperty("enforcing").strip();
        if (enforcingStr.equalsIgnoreCase("true")) {
            enforcing = true;
        } else if (enforcingStr.equalsIgnoreCase("false")) {
            enforcing = false;
        } else {
            throw new IllegalStateException("Invalid boolean for enforcing");
        }

        String loginTimeoutTicksStr = props.getProperty("login_timeout_ticks");
        try {
            loginTimeoutTicks = Integer.parseUnsignedInt(loginTimeoutTicksStr);
        } catch (NumberFormatException e) {
            throw new IllegalStateException("Invalid integer for login_timeout_ticks: {}", e);
        }

        String registrationRequiredStr =
                props.getProperty("registration_required").strip();
        if (registrationRequiredStr.equalsIgnoreCase("true")) {
            registrationRequired = true;
        } else if (registrationRequiredStr.equalsIgnoreCase("false")) {
            registrationRequired = false;
        } else {
            throw new IllegalStateException("Invalid boolean for registration_required");
        }

        String allowRegistrationStr = props.getProperty("allow_registration").strip();
        if (allowRegistrationStr.equalsIgnoreCase("true")) {
            allowRegistration = true;
        } else if (allowRegistrationStr.equalsIgnoreCase("false")) {
            allowRegistration = false;
        } else {
            throw new IllegalStateException("Invalid boolean for allow_registration");
        }

        Constants.LOG.info("AKMC: successfully loaded server config.");
    }

    public void write() {
        try {
            Files.createDirectories(AuthorisedKeysModCore.FILE_PATHS.CONFIG_DIR);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        try (BufferedWriter writer =
                new BufferedWriter(new FileWriter(AuthorisedKeysModCore.FILE_PATHS.SERVER_CONFIG_PATH.toFile()))) {
            writer.write("# AKMC Server Configuration\n#\n");
            writer.write("# This file is automatically generated.\n#\n\n");
            writer.write("enforcing = ");
            writer.write(enforcing ? "true\n" : "false\n");
            writer.write("login_timeout_ticks = %s\n".formatted(loginTimeoutTicks));
            writer.write("registration_required = ");
            writer.write(registrationRequired ? "true\n" : "false\n");
            writer.write("allow_registration = ");
            writer.write(allowRegistration ? "true\n" : "false\n");
        } catch (RuntimeException | IOException e) {
            throw new RuntimeException(e);
        }

        Constants.LOG.info("AKMC: wrote server config.");
    }
}
