package ph.jldvmsrwll1a.authorisedkeysmc;

import java.io.*;
import java.nio.file.Files;
import java.util.Optional;
import java.util.Properties;

public final class ServerConfig {
    private static final Object WRITE_LOCK = new Object();

    public volatile boolean enforcing = true;
    public volatile int loginTimeoutTicks = 1200;
    public volatile boolean registrationRequired = false;
    public volatile boolean allowRegistration = true;
    public volatile boolean skipOnlineAccounts = false;

    public static ServerConfig fromDisk() {
        ServerConfig config = new ServerConfig();
        Properties props = new Properties();

        synchronized (WRITE_LOCK) {
            try (FileReader file = new FileReader(AkmcCore.FILE_PATHS.SERVER_CONFIG_PATH.toFile())) {
                props.load(file);
            } catch (FileNotFoundException e) {
                return config;
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }

        parseBooleanStrictly(props, "enforcing").ifPresent(bool -> {
            config.enforcing = bool;
        });
        parseUnsignedInteger(props, "login_timeout_ticks").ifPresent(value -> {
            config.loginTimeoutTicks = value;
        });
        parseBooleanStrictly(props, "registration_required").ifPresent(bool -> {
            config.registrationRequired = bool;
        });
        parseBooleanStrictly(props, "allow_registration").ifPresent(bool -> {
            config.allowRegistration = bool;
        });
        parseBooleanStrictly(props, "skip_online_accounts").ifPresent(bool -> {
            config.skipOnlineAccounts = bool;
        });

        return config;
    }

    public void write() {
        synchronized (WRITE_LOCK) {
            try {
                Files.createDirectories(AkmcCore.FILE_PATHS.CONFIG_DIR);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }

            try (BufferedWriter writer =
                         new BufferedWriter(new FileWriter(AkmcCore.FILE_PATHS.SERVER_CONFIG_PATH.toFile()))) {
                writer.write("# AKMC Server Configuration\n#\n");
                writer.write("# This file is automatically generated.\n#\n\n");
                writer.write("enforcing = ");
                writer.write(enforcing ? "true\n" : "false\n");
                writer.write("login_timeout_ticks = %s\n".formatted(loginTimeoutTicks));
                writer.write("registration_required = ");
                writer.write(registrationRequired ? "true\n" : "false\n");
                writer.write("allow_registration = ");
                writer.write(allowRegistration ? "true\n" : "false\n");
                writer.write("skip_online_accounts = ");
                writer.write(skipOnlineAccounts ? "true\n" : "false\n");
            } catch (RuntimeException | IOException e) {
                throw new RuntimeException(e);
            }

            Constants.LOG.info("AKMC: wrote server config.");
        }
    }

    private static Optional<Boolean> parseBooleanStrictly(Properties properties, String key) {
        String value = properties.getProperty(key);

        if (value == null) {
            return Optional.empty();
        }

        value = value.strip();

        if (value.equalsIgnoreCase("true")) {
            return Optional.of(true);
        } else if (value.equalsIgnoreCase("false")) {
            return Optional.of(false);
        } else {
            throw new IllegalStateException("Invalid boolean for property '%s'".formatted(key));
        }
    }

    private static Optional<Integer> parseUnsignedInteger(Properties properties, String key) {
        String value = properties.getProperty("login_timeout_ticks");

        if (value == null) {
            return Optional.empty();
        }

        try {
            return Optional.of(Integer.parseUnsignedInt(value.strip()));
        } catch (NumberFormatException e) {
            throw new IllegalStateException("Invalid unsigned integer for '%s'".formatted(key), e);
        }
    }
}
